---
- hostname: name={{ fqdn }}

- timezone:
    name: "{{ timezone }}"

- name: Re-gather facts
  action: setup
  when: inventory_hostname != fqdn

- name: Update and Clean packages
  apt:
    upgrade: safe
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install base packages
  apt:
    state: latest
    pkg:
      - git
      - bc
      - jq
      - wget
      - curl
      - unattended-upgrades
      - apt-listchanges
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
      - acpid
      - dkms
      - python-pip
      - dnsutils
      - iotop
      - htop
      - glances
      - iftop
      - ngrep
      - iptraf
      - tree
      - ncdu
      - sysstat
      - mlocate
      - ntpdate
      - iptables-persistent
      - vim
      - tmux

- name: Enable sysctl setting
  sysctl:
    sysctl_file: /etc/sysctl.d/90-ansible.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: net.ipv4.tcp_window_scaling
      value: 1
    - name: net.core.rmem_max
      value: 67108864
    - name: net.core.wmem_max
      value: 67108864
    - name: net.ipv4.tcp_rmem
      value: "4096 87380 33554432"
    - name: net.ipv4.tcp_wmem
      value: "4096 87380 33554432"
    - name: net.ipv4.tcp_congestion_control
      value: bbr
    - name: fs.file-max
      value: 100000
    - name: vm.swappiness
      value: 10
    - name: vm.dirty_background_ratio
      value: 10
    - name: vm.dirty_ratio
      value: 15
    - name: net.core.somaxconn
      value: 1024
    - name: net.core.netdev_max_backlog
      value: 50000
    - name: net.ipv4.tcp_max_syn_backlog
      value: 30000
    - name: net.ipv4.tcp_max_tw_buckets
      value: 2000000
    - name: net.ipv4.tcp_tw_reuse
      value: 1
    - name: net.ipv4.tcp_mtu_probing
      value: 1
    - name: net.ipv4.tcp_sack
      value: 1
    - name: net.ipv4.tcp_adv_win_scale
      value: 2
    - name: net.ipv4.tcp_rfc1337
      value: 1
    - name: net.ipv4.tcp_fin_timeout
      value: 10
    - name: net.ipv4.tcp_slow_start_after_idle
      value: 0
    - name: net.ipv4.udp_rmem_min
      value: 8192
    - name: net.ipv4.udp_wmem_min
      value: 8192
    - name: net.ipv4.conf.all.accept_source_route
      value: 0
    - name: net.ipv4.conf.all.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.secure_redirects
      value: 0
    - name: net.core.default_qdisc
      value: fq

- name: Set sysctl vars
  command: sysctl --system

- iptables:
    action: insert
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- iptables:
    action: insert
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    jump: ACCEPT

- name: Disable ssh remote root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - Restart sshd

- name: Esnable ssh strict mode
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?StrictModes"
    line: "StrictModes yes"
    state: present
  notify:
    - Restart sshd

- name: Disable ssh password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication no"
    - regexp: "^#?UsePAM"
      line: "UsePAM no"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
  notify:
    - Restart sshd
