---
- name: Create pi-hole directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/pihole
    - /etc/dnsmasq.d

- name: Create and start container
  docker_container:
    networks_cli_compatible: yes
    name: pi-hole
    image: pihole/pihole:latest
    pull: yes
    network_mode: host
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "ABC123abc!"
      ServerIP: 192.168.1.10
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - /etc/pihole/:/etc/pihole/
      - /etc/dnsmasq.d/:/etc/dnsmasq.d/
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    state: started
